In [1]:
import numpy as np

In [5]:
data = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])

In [6]:
data

array([[ 0.1,  0.2,  0.3],
       [ 0.4,  0.5,  0.6]])

In [7]:
data * 10

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [8]:
data + data

array([[ 0.2,  0.4,  0.6],
       [ 0.8,  1. ,  1.2]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7.5, 8, 0, 1]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int64')

In [24]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [25]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [26]:
np.empty((2, 3, 2))

array([[[ -3.10503618e+231,   1.72723382e-077],
        [  3.45845952e-323,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [29]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [32]:
arr = np.array([1, 2, 3, 4, 5])

In [33]:
arr.dtype

dtype('int64')

In [34]:
float_arr = arr.astype(np.float64)

In [35]:
float_arr.dtype

dtype('float64')